name: Bug Report
description: Create a report to help us improve
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please view our [Technical Support Guide](https://github.com/microsoft/BotFramework-WebChat/tree/main/docs/TECHNICAL_SUPPORT_GUIDE.md) before filing a new issue.

        [GitHub issues](https://github.com/microsoft/botframework-webchat/issues) should be used for bugs and feature requests. See the [Technical Support Guide](https://github.com/microsoft/BotFramework-WebChat/tree/main/docs/TECHNICAL_SUPPORT_GUIDE.md) to get support related to Bot Framework and Web Chat.
  - type: checkboxes
    attributes:
      label: Accessibility issue
      options:
        - label: Yes, this is an accessibility issue.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
        Be sure to remove or obscure personally identifiable information from your code and screenshots
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        To determine what version of Web Chat you are running, open your browser's development tools, and paste the following line of code into the console.
        
        ```js
        [].map.call(document.head.querySelectorAll('meta[name^="botframework-"]'), function (meta) { return meta.outerHTML; }).join('\n')
        ```
      value: 4.15.3
    validations:
      required: true
  - type: dropdown
    id: distribution
    attributes:
      label: Distribution
      description: |
        Which distribution are you using Web Chat from?
      options:
        - Bundle (webchat.js)
        - NPM
        - IFRAME
        - Unrelated
    validations:
      required: true
  - type: dropdown
    id: hosting-environment
    attributes:
      label: Hosting environment
      description: |
        Which hosting environment does this issue affect?
      options:
        - Web apps
        - Dynamics 365 Omnichannel
        - SharePoint
        - PowerApps
        - Cordova/PhoneGap
        - WebView on React Native
        - Others or unrelated
    validations:
      required: true
  - type: dropdown
    id: browser-and-platform
    attributes:
      label: Browser and platform
      description: |
        Which browsers and platforms do the issue happened? Please make sure the issue continued to repro on latest version of the browser.
      multiple: true
      options:
        - "Browser: Edge"
        - "Browser: Chrome"
        - "Browser: Firefox"
        - "Browser: Safari"
        - "Browser: IE Mode"
        - "Platform: Windows"
        - "Platform: macOS"
        - "Platform: iOS/iPadOS"
        - "Platform: Android"
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: |
        Which area does this issue related to?

        If this issue is related to Adaptive Card, please verify this issue does not repro on [Adaptive Cards Designer](https://adaptivecards.io/designer/).
      options:
        - Adaptive Card
        - Chat history
        - Customization
        - Notification
        - OAuth
        - Rich cards (hero card, thumbnail card, etc)
        - Send box
        - Speech
        - Suggested action
        - Others
    validations:
      required: true
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: |
        Give a clear and concise description of what the bug is.
        Please be sure to add screenshots of the console errors in your browser, if there are any.
    validations:
      required: true
  - type: textarea
    id: console-log
    attributes:
      label: Console log
      description: If errors are logged to console (<kbd>F12</kbd>), please copy them here.
  - type: textarea
    id: repro-steps
    attributes:
      label: Repro steps
      description: |
        Please list precise steps to reproduce the issue.
      value: |
        1. Navigate to ...
        1. Click on ...
        1. Type "..." in the send box
    validations:
      required: true
  - type: textarea
    id: expected-and-actual
    attributes:
      label: Expected and actual behavior
      description: Give a clear and concise description of what you expect to happen and what actually happened.
      value: |
        Expected:

        Actual:
    validations:
      required: true
  - type: textarea
    id: adaptive-card-json
    attributes:
      label: Adaptive Card JSON
      description: If this issue related to Adaptive Cards, please paste the JSON of the card below.
      placeholder: |
        ```json
        {
          "type": "AdaptiveCard",
          "body": []
          "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
          "version": "1.5"
        }
        ```
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
